# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fab663ada663f2156ebc3fec8382ff71e32c4d1409a21e4f8e2c9cd68233c074f77d6dab3a166779b38da29622eb3cf8b43b355496d5971a8e92b379f53b381

test:
  secret_key_base: 18203a789122dde05d844744ba49200fc84204676c51e11e4d7ada54ee2cd46e2afb3106f6b3f9bc6f34f49ce0d6b11217f47c188040379f2bbb2a32c41e02c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
